// <auto-generated />

using Avalonia;
using Avalonia.Controls;
using Avalonia.Markup.Xaml;

namespace BurgerBuilder.Avalonia
{
    partial class MainWindow
    {
        public global::Avalonia.Controls.Button buttonMenuI;
        public global::Avalonia.Controls.Button buttonMenuII;
        public global::Avalonia.Controls.Button buttonSalad;
        public global::Avalonia.Controls.Button buttonCheese;
        public global::Avalonia.Controls.Button buttonMeat;
        public global::Avalonia.Controls.Button buttonTomato;
        public global::Avalonia.Controls.Button buttonSkip;

        /// <summary>
        /// Wires up the controls and optionally loads XAML markup and attaches dev tools (if Avalonia.Diagnostics package is referenced).
        /// </summary>
        /// <param name="loadXaml">Should the XAML be loaded into the component.</param>
        /// <param name="attachDevTools">Should the dev tools be attached.</param>

        public void InitializeComponent(bool loadXaml = true, bool attachDevTools = true)
        {
            if (loadXaml)
            {
                AvaloniaXamlLoader.Load(this);
            }

#if DEBUG
            if (attachDevTools)
            {
                this.AttachDevTools();
            }
#endif

            buttonMenuI = this.FindControl<global::Avalonia.Controls.Button>("buttonMenuI");
            buttonMenuII = this.FindControl<global::Avalonia.Controls.Button>("buttonMenuII");
            buttonSalad = this.FindControl<global::Avalonia.Controls.Button>("buttonSalad");
            buttonCheese = this.FindControl<global::Avalonia.Controls.Button>("buttonCheese");
            buttonMeat = this.FindControl<global::Avalonia.Controls.Button>("buttonMeat");
            buttonTomato = this.FindControl<global::Avalonia.Controls.Button>("buttonTomato");
            buttonSkip = this.FindControl<global::Avalonia.Controls.Button>("buttonSkip");
        }
    }
}
